### ISSUE TITLE
编译后的服务器内加载

### ISSUE THREAD

**Issue by IHIntary** [SakuraKoi/BridgingSkin#2]
在编译时不会出现问题 但是在编译后放入服务器加载之后服务器表示找不到gsonbuilder
有解吗= =我是没想出来啥好办法= =（为什么在这里提issue的总是我 我得谢罪）
[22:17:15 ERROR]: Could not load 'plugins/BridgingSkin.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: sakura/lib/com/google/gson/GsonBuilder
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [server.jar:git-Spigot-21fe707-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [server.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.NoClassDefFoundError: sakura/lib/com/google/gson/GsonBuilder
at sakura.kooi.BridgingSkin.BridgingSkin.<clinit>(BridgingSkin.java:31) ~[?:?]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_232]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_232]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[server.jar:git-Spigot-21fe707-e1ebe52]
... 6 more
Caused by: java.lang.ClassNotFoundException: sakura.lib.com.google.gson.GsonBuilder
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_232]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
at sakura.kooi.BridgingSkin.BridgingSkin.<clinit>(BridgingSkin.java:31) ~[?:?]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_232]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_232]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[server.jar:git-Spigot-21fe707-e1ebe52]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[server.jar:git-Spigot-21fe707-e1ebe52]
... 6 more

**Comment by SakuraKoi** [comment]
gson依赖你得打包进jar啊喂, libs目录里面
